language: node_js

node_js:
  - "6.10.3"

script:
  - npm run build

before_script:
  - npm install

deploy:
  skip_cleanup: true
  provider: script
  github_token: $GITHUB_TOKEN
  script: sh .travis/push_to_prod.sh
  on:
    branch: master
